id = "curlpit"
name = "Curlpit"
description = "Syntax highlighting for Curlpit .curl request files"
version = "0.1.0"
schema_version = 1
authors = ["Curlpit Contributors"]
repository = "https://github.com/curlpit/curlpit"

languages = ["languages/curl"]

[grammars.http]
repository = "https://github.com/rest-nvim/tree-sitter-http"
rev = "db8b4398de90b6d0b6c780aba96aaa2cd8e9202c"
