[alias]
example = "run -- --config examples examples/httpbin-get.curl"
interactive = "run -- --config examples"
mac = "build --release --target aarch64-apple-darwin"
build-mac-arm64 = "build --release --target aarch64-apple-darwin"
build-mac-x64 = "build --release --target x86_64-apple-darwin"
build-linux-arm64 = "build --release --target aarch64-unknown-linux-gnu"
build-linux-x64 = "build --release --target x86_64-unknown-linux-gnu"
cov = "llvm-cov --workspace --summary-only"
