name: Publish npm Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-22.04
    if: ${{ github.event.release.prerelease == false }}
    permissions:
      contents: read
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          persist-credentials: false
          submodules: recursive
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Publish to npm
        working-directory: packages/npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
