name: Publish Brew Formula

on:
  workflow_run:
    workflows: ["Release"]
    types: ["completed"]

jobs:
  publish-brew:
    runs-on: ubuntu-22.04
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          startsWith(github.event.workflow_run.head_branch, 'v') }}
    permissions:
      contents: read
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          persist-credentials: false
          submodules: recursive
      - name: Publish Brew formula (TODO)
        run: echo "Brew publish steps go here"
