name: Publish npm Package

on:
  workflow_run:
    workflows: ["Release"]
    types: ["completed"]

jobs:
  publish-npm:
    runs-on: ubuntu-22.04
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          startsWith(github.event.workflow_run.head_branch, 'v') }}
    permissions:
      contents: read
    steps:
      - name: Checkout release commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          persist-credentials: false
          submodules: recursive
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Publish to npm
        working-directory: packages/npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
