name: Publish Deno Package

on:
  release:
    types: [published]

jobs:
  publish-deno:
    runs-on: ubuntu-22.04
    if: ${{ github.event.release.prerelease == false }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          persist-credentials: false
          submodules: recursive
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.45.5
      - name: Publish to JSR
        working-directory: packages/deno
        run: deno publish
